"""pcq.agent.init — scaffold a CQ-runnable ML experiment.

`pcq init-experiment` 가 호출하는 모듈.
세 가지 style:
  trainer    — pcq.Trainer.from_cfg(cfg) (기본, preset 필수)
  experiment — pcq.Experiment subclass
  script     — framework-agnostic contract script (sklearn/XGBoost 등)

생성 파일 (style 별 분기):
  cq.yaml                 — Hub 가 읽는 런타임 계약 (CQ service contract spec)
  train.py                — style 에 따른 entrypoint 템플릿
  recipes/__init__.py     — 빈 marker (trainer/experiment 만)
  recipes/local.py        — 사용자 custom atom 등록 위치 (trainer/experiment 만)
  pcq_atoms.py            — project atoms entry (trainer/experiment 만)
  atoms/__init__.py       — atoms 디렉터리 (trainer/experiment 만)
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


_TRAINER_TEMPLATE = '''"""Generated by `pcq init-experiment --style trainer`. Edit at will.

cfg["preset"] 가 recipe 를 선택, cfg["_overrides_data"] 는
`pcq apply-plan` 이 관리하는 atom override 를 AtomRef 로 deserialize 한다.

Project-local atoms 은 pcq_atoms.py / atoms/*.py 에서 자동 import.
"""
import pcq

# Auto-load project atoms (silent if pcq_atoms.py absent)
try:
    import pcq_atoms  # noqa: F401
except ImportError:
    pass

cfg = pcq.config()
pcq.seed_everything(cfg.get("seed", 42))

trainer = pcq.Trainer.from_cfg(cfg)
trainer.fit()
'''


_EXPERIMENT_TEMPLATE = '''"""Generated by `pcq init-experiment --style experiment`."""
import pcq
from pcq import Experiment

try:
    import pcq_atoms  # noqa: F401
except ImportError:
    pass


class MyExperiment(Experiment):
    def build_dataset(self, split):
        return pcq.examples.datasets.fake(num_samples=128, num_classes=10)

    def build_model(self):
        return pcq.examples.models.mlp(3 * 32 * 32, [128], 10)

    def build_loss(self):
        return pcq.loss.cross_entropy()

    def build_optimizer(self, params):
        return pcq.examples.optim.adamw(params, lr=self.cfg.get("lr", 1e-3))

    def training_step(self, batch):
        x, y = batch
        logits = self.model(x)
        loss = self.loss_fn(logits, y)
        return loss, {"acc": pcq.metric.accuracy(logits, y).item()}

    def eval_step(self, batch):
        x, y = batch
        logits = self.model(x)
        loss = self.loss_fn(logits, y)
        return {"loss": loss.item(), "acc": pcq.metric.accuracy(logits, y).item()}


cfg = pcq.config()
pcq.seed_everything(cfg.get("seed", 42))
MyExperiment(cfg=cfg).fit()
'''


_SCRIPT_TEMPLATE = '''"""Generated by `pcq init-experiment --style script`.

Plain contract script — use any ML library. Honor the CQ contract:
read config, emit declared metrics, write standard artifacts.

pcq.save_all() writes 6 contract artifacts in one call:
config.json, metrics.json, manifest.json, run_summary.json,
run_record.json (v1.16+ SSOT), validation_report.json (post-run gates).

To opt out of run_record/validation_report, pass finalize=False to save_all.
"""
import pcq

cfg = pcq.config()
out = pcq.output_dir()
pcq.seed_everything(cfg.get("seed", 42))

# ── Replace this block with your framework code ────────────────────
# Example: sklearn (uncomment after `uv add scikit-learn joblib`)
# import joblib
# from sklearn.datasets import load_iris
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import train_test_split
#
# X, y = load_iris(return_X_y=True)
# X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2,
#                                           random_state=cfg.get("seed", 42))
# model = RandomForestClassifier(n_estimators=cfg.get("n_estimators", 100))
# model.fit(X_tr, y_tr)
# acc = float(model.score(X_te, y_te))
# joblib.dump(model, out / "model.pkl")

acc = 0.5
# ─────────────────────────────────────────────────────────────────────

pcq.log(epoch=0, eval_acc=acc)

pcq.save_all(
    history=[{"epoch": 0, "eval_acc": acc}],
    status="completed",
    artifacts={"model": "model.pkl"} if (out / "model.pkl").exists() else None,
)
'''


_LOCAL_RECIPES_TEMPLATE = '''"""Project-local custom atoms / recipes.

여기에 등록한 custom atom 은 `Trainer(model="my_x")` 와
`pcq atoms list` 에서 발견할 수 있다.

예시:

    import pcq

    @pcq.register_model("my_dental_unet", meta={
        "tasks": ["segmentation"],
        "params": {"in_channels": {"type": "int", "default": 3}},
    })
    def factory(in_channels=3, num_classes=2):
        return MyDentalUNet(in_channels=in_channels, num_classes=num_classes)
"""
'''


_CQ_ATOMS_PY_TEMPLATE = '''"""Project-local atom registration entry point.

This file is imported by train.py and by `pcq inspect`. Add atom modules to
the import list below as you scaffold them via `pcq atoms scaffold`.

Default behavior: load all atoms/*.py automatically when the directory exists.
"""
import importlib
from pathlib import Path

_ATOMS_DIR = Path(__file__).parent / "atoms"
if _ATOMS_DIR.is_dir():
    for _py in sorted(_ATOMS_DIR.glob("*.py")):
        if _py.name.startswith("_"):
            continue
        importlib.import_module(f"atoms.{_py.stem}")
'''


# 기본 메트릭 — preset 메타에서 declared_metrics 가 비어 있을 때만 사용.
_DEFAULT_METRICS = ["epoch", "train_loss", "train_acc", "eval_loss", "eval_acc"]

# script style 의 기본 메트릭 — preset 없으므로 generic
_SCRIPT_DEFAULT_METRICS = ["epoch", "eval_acc"]


_VALID_STYLES = ("trainer", "experiment", "script")


@dataclass
class InitResult:
    """init_experiment 결과 — JSON-safe."""

    schema_version: int = 1
    project_root: str = ""
    files_created: list[str] = field(default_factory=list)
    files_skipped: list[str] = field(default_factory=list)
    preset: str = ""
    name: str = ""
    style: str = "trainer"
    warnings: list[str] = field(default_factory=list)
    agent_install: dict | None = None

    def to_dict(self) -> dict:
        return {
            "schema_version": self.schema_version,
            "project_root": self.project_root,
            "files_created": self.files_created,
            "files_skipped": self.files_skipped,
            "preset": self.preset,
            "name": self.name,
            "style": self.style,
            "warnings": self.warnings,
            "agent_install": self.agent_install,
        }


_PYPROJECT_TEMPLATE = '''\
[project]
name = "{slug}"
version = "0.1.0"
description = "Generated by `pcq init-experiment` — fill in real description."
requires-python = ">=3.10"
dependencies = [
    "pcq>={pcq_version}",{extras_lines}
]

# This is an experiment project, not a redistributable package.
# `package = false` skips wheel build — uv only resolves dependencies.
[tool.uv]
package = false
'''


def _build_pyproject(slug: str, pcq_version: str,
                     requires_extras: list[str]) -> str:
    """preset.requires_extras → pcq[X,Y] dependency 추가."""
    extras_lines = ""
    if requires_extras:
        joined = ",".join(sorted(set(requires_extras)))
        extras_lines = f'\n    "pcq[{joined}]>={pcq_version}",'
        # primary pcq dep은 위에 이미 있으므로 pcq[extras]로 보강
    safe_slug = slug.replace("/", "-").replace("_", "-").lower()
    return _PYPROJECT_TEMPLATE.format(
        slug=safe_slug, pcq_version=pcq_version, extras_lines=extras_lines,
    )


def init_experiment(
    output_dir: str | Path,
    preset: str | None = None,
    name: str | None = None,
    force: bool = False,
    style: str = "trainer",
    with_pyproject: bool = False,
    agent: str | None = None,
) -> InitResult:
    """Scaffold cq.yaml + train.py (+ atoms/ for trainer/experiment).

    Args:
        output_dir: 프로젝트 루트 (생성/덮어쓰기 대상).
        preset: 등록된 recipe 이름 (예: "vision/fake_smoke").
                trainer style 에서 필수, script/experiment 에서는 무시.
        name: cq.yaml.name 값. None 이면 preset 의 / 를 - 로 치환,
              preset 이 없으면 "pcq-experiment".
        force: True 면 기존 파일 덮어씀. False 면 skip.
        style: "trainer" | "experiment" | "script".
        with_pyproject: True 면 pyproject.toml 도 생성 (pcq dep + preset extras).
                       reproducibility evidence (lockfile_sha256) 위해 권장.
        agent: Optional agent runtime asset install target:
               "codex" | "claude" | "both".
    """
    from pcq.agent.yaml_io import write_yaml

    if style not in _VALID_STYLES:
        raise ValueError(
            f"unknown style {style!r}; supported: {'/'.join(_VALID_STYLES)}"
        )

    if style == "trainer" and not preset:
        raise ValueError("trainer style requires --preset")

    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    # name 결정
    if name is None:
        if preset:
            name = preset.replace("/", "-")
        else:
            name = "pcq-experiment"

    result = InitResult(
        project_root=str(out),
        preset=preset or "",
        name=name,
        style=style,
    )

    # preset metadata 조회 — declared_metrics 추출. 실패해도 계속 (warn 만).
    if style == "trainer":
        declared_metrics = list(_DEFAULT_METRICS)
        try:
            from pcq.agent import recipe_meta

            meta = recipe_meta(preset)
            if meta.get("import_error"):
                result.warnings.append(
                    f"preset metadata fetch had import_error: "
                    f"{meta['import_error']}"
                )
            if meta.get("declared_metrics"):
                declared_metrics = list(meta["declared_metrics"])
        except Exception as e:  # noqa: BLE001
            result.warnings.append(f"preset metadata fetch failed: {e}")
    elif style == "experiment":
        declared_metrics = list(_DEFAULT_METRICS)
    else:
        declared_metrics = list(_SCRIPT_DEFAULT_METRICS)

    # ── cq.yaml ─────────────────────────────────────────────────────
    cq_yaml: dict = {
        "name": name,
        "cmd": "uv run python train.py",
        "configs": {
            "output_dir": "output",
            "epochs": 1,
            "batch_size": 16,
            "lr": 0.001,
            "seed": 42,
            "_metrics_declared": declared_metrics,
        },
        "metrics": declared_metrics,
        "artifacts": ["output/"],
    }
    if style == "trainer" and preset:
        # configs 맨 앞에 preset 두기
        cq_yaml["configs"] = {
            "preset": preset,
            **cq_yaml["configs"],
        }
    cq_path = out / "cq.yaml"
    if cq_path.exists() and not force:
        result.files_skipped.append("cq.yaml")
    else:
        write_yaml(cq_yaml, cq_path)
        result.files_created.append("cq.yaml")

    # ── train.py ────────────────────────────────────────────────────
    template_map = {
        "trainer": _TRAINER_TEMPLATE,
        "experiment": _EXPERIMENT_TEMPLATE,
        "script": _SCRIPT_TEMPLATE,
    }
    train_path = out / "train.py"
    if train_path.exists() and not force:
        result.files_skipped.append("train.py")
    else:
        train_path.write_text(template_map[style], encoding="utf-8")
        result.files_created.append("train.py")

    # ── atom infrastructure (trainer / experiment only) ─────────────
    if style in ("trainer", "experiment"):
        # recipes/__init__.py + recipes/local.py
        recipes_dir = out / "recipes"
        recipes_dir.mkdir(exist_ok=True)
        init_path = recipes_dir / "__init__.py"
        if not init_path.exists():
            init_path.write_text("", encoding="utf-8")
            result.files_created.append("recipes/__init__.py")

        local_path = recipes_dir / "local.py"
        if local_path.exists() and not force:
            result.files_skipped.append("recipes/local.py")
        else:
            local_path.write_text(_LOCAL_RECIPES_TEMPLATE, encoding="utf-8")
            result.files_created.append("recipes/local.py")

        # pcq_atoms.py + atoms/__init__.py
        cq_atoms_path = out / "pcq_atoms.py"
        if cq_atoms_path.exists() and not force:
            result.files_skipped.append("pcq_atoms.py")
        else:
            cq_atoms_path.write_text(_CQ_ATOMS_PY_TEMPLATE, encoding="utf-8")
            result.files_created.append("pcq_atoms.py")

        atoms_dir = out / "atoms"
        atoms_dir.mkdir(exist_ok=True)
        atoms_init_path = atoms_dir / "__init__.py"
        if not atoms_init_path.exists():
            atoms_init_path.write_text("", encoding="utf-8")
            result.files_created.append("atoms/__init__.py")

    # ── pyproject.toml (옵션) ───────────────────────────────────────
    if with_pyproject:
        pyproject_path = out / "pyproject.toml"
        if pyproject_path.exists() and not force:
            result.files_skipped.append("pyproject.toml")
        else:
            from pcq import __version__ as _pcq_version
            requires_extras: list[str] = []
            if style == "trainer" and preset:
                try:
                    from pcq.agent import recipe_meta
                    meta = recipe_meta(preset)
                    requires_extras = list(meta.get("requires_extras") or [])
                except Exception:
                    pass
            pyproject_path.write_text(
                _build_pyproject(name, _pcq_version, requires_extras),
                encoding="utf-8",
            )
            result.files_created.append("pyproject.toml")

    # ── agent runtime assets (옵션) ─────────────────────────────────
    if agent and agent != "none":
        from pcq.agent.install import install_agent_assets

        install_result = install_agent_assets(
            out,
            target=agent,
            force=force,
            dry_run=False,
        )
        result.agent_install = install_result.to_dict()

    return result
