"""pcq.agent.init — scaffold a CQ-runnable ML experiment.

`pcq init-experiment` 가 호출하는 모듈. v4.0 부터 contract script 만 지원.

생성 파일:
  cq.yaml  — Hub 가 읽는 런타임 계약 (CQ service contract spec)
  train.py — contract script entrypoint 템플릿
  pyproject.toml (옵션) — pcq 의존성 + reproducibility evidence (lockfile_sha256)
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


_SCRIPT_TEMPLATE = '''"""Generated by `pcq init-experiment`.

Plain contract script — use any ML library. Honor the CQ contract:
read config, emit declared metrics, write standard artifacts.

pcq.save_all() writes 6 contract artifacts in one call:
config.json, metrics.json, manifest.json, run_summary.json,
run_record.json (SSOT), validation_report.json (post-run gates).

To opt out of run_record/validation_report, pass finalize=False to save_all.
"""
import pcq

cfg = pcq.config()
out = pcq.output_dir()
pcq.seed_everything(cfg.get("seed", 42))

# ── Replace this block with your framework code ────────────────────
# Example: sklearn (uncomment after `uv add scikit-learn joblib`)
# import joblib
# from sklearn.datasets import load_iris
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import train_test_split
#
# X, y = load_iris(return_X_y=True)
# X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2,
#                                           random_state=cfg.get("seed", 42))
# model = RandomForestClassifier(n_estimators=cfg.get("n_estimators", 100))
# model.fit(X_tr, y_tr)
# acc = float(model.score(X_te, y_te))
# joblib.dump(model, out / "model.pkl")

acc = 0.5
# ─────────────────────────────────────────────────────────────────────

pcq.log(epoch=0, eval_acc=acc)

pcq.save_all(
    history=[{"epoch": 0, "eval_acc": acc}],
    status="completed",
    artifacts={"model": "model.pkl"} if (out / "model.pkl").exists() else None,
)
'''


# script style 의 기본 메트릭 — preset 없으므로 generic
_SCRIPT_DEFAULT_METRICS = ["epoch", "eval_acc"]


@dataclass
class InitResult:
    """init_experiment 결과 — JSON-safe."""

    schema_version: int = 1
    project_root: str = ""
    files_created: list[str] = field(default_factory=list)
    files_skipped: list[str] = field(default_factory=list)
    name: str = ""
    style: str = "script"
    warnings: list[str] = field(default_factory=list)
    agent_install: dict | None = None

    def to_dict(self) -> dict:
        return {
            "schema_version": self.schema_version,
            "project_root": self.project_root,
            "files_created": self.files_created,
            "files_skipped": self.files_skipped,
            "name": self.name,
            "style": self.style,
            "warnings": self.warnings,
            "agent_install": self.agent_install,
        }


_PYPROJECT_TEMPLATE = '''\
[project]
name = "{slug}"
version = "0.1.0"
description = "Generated by `pcq init-experiment` — fill in real description."
requires-python = ">=3.10"
dependencies = [
    "pcq>={pcq_version}",
]

# This is an experiment project, not a redistributable package.
# `package = false` skips wheel build — uv only resolves dependencies.
[tool.uv]
package = false
'''


def _build_pyproject(slug: str, pcq_version: str) -> str:
    """generate minimal pyproject for an experiment project."""
    safe_slug = slug.replace("/", "-").replace("_", "-").lower()
    return _PYPROJECT_TEMPLATE.format(
        slug=safe_slug, pcq_version=pcq_version,
    )


def init_experiment(
    output_dir: str | Path,
    name: str | None = None,
    force: bool = False,
    with_pyproject: bool = False,
    agent: str | None = None,
) -> InitResult:
    """Scaffold cq.yaml + train.py contract script.

    v4.0: contract script 만 지원 (Trainer/Experiment 제거).

    Args:
        output_dir: 프로젝트 루트 (생성/덮어쓰기 대상).
        name: cq.yaml.name 값. None 이면 "pcq-experiment".
        force: True 면 기존 파일 덮어씀. False 면 skip.
        with_pyproject: True 면 pyproject.toml 도 생성. reproducibility evidence
                       (lockfile_sha256) 위해 권장.
        agent: Optional agent runtime asset install target:
               "codex" | "claude" | "both".
    """
    from pcq.agent.yaml_io import write_yaml

    out = Path(output_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    # name 결정
    if name is None:
        name = "pcq-experiment"

    result = InitResult(
        project_root=str(out),
        name=name,
        style="script",
    )

    declared_metrics = list(_SCRIPT_DEFAULT_METRICS)

    # ── cq.yaml ─────────────────────────────────────────────────────
    cq_yaml: dict = {
        "name": name,
        "cmd": "uv run python train.py",
        "configs": {
            "output_dir": "output",
            "epochs": 1,
            "batch_size": 16,
            "lr": 0.001,
            "seed": 42,
            "_metrics_declared": declared_metrics,
        },
        "metrics": declared_metrics,
        "artifacts": ["output/"],
    }
    cq_path = out / "cq.yaml"
    if cq_path.exists() and not force:
        result.files_skipped.append("cq.yaml")
    else:
        write_yaml(cq_yaml, cq_path)
        result.files_created.append("cq.yaml")

    # ── train.py ────────────────────────────────────────────────────
    train_path = out / "train.py"
    if train_path.exists() and not force:
        result.files_skipped.append("train.py")
    else:
        train_path.write_text(_SCRIPT_TEMPLATE, encoding="utf-8")
        result.files_created.append("train.py")

    # ── pyproject.toml (옵션) ───────────────────────────────────────
    if with_pyproject:
        pyproject_path = out / "pyproject.toml"
        if pyproject_path.exists() and not force:
            result.files_skipped.append("pyproject.toml")
        else:
            from pcq import __version__ as _pcq_version
            pyproject_path.write_text(
                _build_pyproject(name, _pcq_version),
                encoding="utf-8",
            )
            result.files_created.append("pyproject.toml")

    # ── agent runtime assets (옵션) ─────────────────────────────────
    if agent and agent != "none":
        from pcq.agent.install import install_agent_assets

        install_result = install_agent_assets(
            out,
            target=agent,
            force=force,
            dry_run=False,
        )
        result.agent_install = install_result.to_dict()

    return result
